### ISSUE TITLE
Fix Zed release

### ISSUE THREAD

**Issue by jnatherley** [MatthiasGrandl/loungy#10]
```
/crates/gpui/src/element.rs:132:57
    |
132 |     fn render(&mut self, cx: &mut ViewContext<Self>) -> impl IntoElement;
    |                                                         ^^^^^^^^^^^^^^^^
    |
```
A number of errors when running `cargo run dev`, assuming because the zed package is pulled from GitHub master

**Comment by MatthiasGrandl** [comment]
No this is an unsupported rust version. There has been another issue with this same error.

**Comment by MatthiasGrandl** [comment]
See #2

**Comment by jnatherley** [comment]
I didn't check the Cargo.toml, cheers!
