### ISSUE TITLE
Transparency

### ISSUE THREAD

**Issue by jafioti** [MatthiasGrandl/Loungy#13]
Hi! Amazing work getting a useful app up in GPUI so quick.

Do you know if it's possible to add transparency? It would really fit the theme of the rest of macos and spotlight search. I'd absolutely love something like this:
<img width="1196" alt="Screenshot 2024-02-10 at 11 25 47 PM" src="https://github.com/MatthiasGrandl/loungy/assets/13525371/124d23cb-c0cd-4151-8a3f-490fc468dd32">

**Comment by MatthiasGrandl** [comment]
Currently there is no support for this upstream. Once there is, it will be quite easy to add.

**Comment by jafioti** [comment]
Would you happen to know what would be needed in GPUI for this? I'm happy to contribute to it, just don't know where to start

**Comment by MatthiasGrandl** [comment]
@jafioti maybe check this repo for inspo: https://github.com/tauri-apps/window-vibrancy

**Comment by tpisto** [comment]
https://github.com/jansol is working on that: https://github.com/zed-industries/zed/issues/5040

**Comment by MatthiasGrandl** [comment]
@tpisto jup I have been following along on Discord. I am sure whenever the PR is up it will be merged pretty quickly and I’ll add support to Loungy.
