### ISSUE TITLE
Supporting cargo install

### ISSUE THREAD

**Issue by egemengol** [MatthiasGrandl/Loungy#15]
Would it be possible to support `cargo install loungy` for ease of setup and upgrades?

Also, can I override spotlight via changing the key binding?

**Comment by MatthiasGrandl** [comment]
> Would it be possible to support cargo install loungy for ease of setup and upgrades?

Loungy is still very early in development and there is no official release yet. I want to support common package managers as soon as possible, including homebrew. Not sure how well cargo works for distributing desktop applications though.

> Also, can I override spotlight via changing the key binding?

That will definitely be possible. At the moment the hotkey is still hardcoded to Opt+Cmd+Ctrl+Space but I'll be working on rebindable hotkeys for Loungy and it's subcommands soon.

**Comment by MatthiasGrandl** [comment]
appears to work:

```
cargo install -F bitwarden --git https://github.com/MatthiasGrandl/Loungy
```

Then just run it with:
```
~/.cargo/bin/loungy
```

**Comment by MatthiasGrandl** [comment]
@egemengol you can now rebind hotkeys. it's still a bit sketchy but basic hotkeys like `cmd+space` should work. You need to first unbind spotlight in the macos system settings:

<img width="912" alt="image" src="https://github.com/MatthiasGrandl/Loungy/assets/50196894/46941404-d584-4543-ade3-0d5d0894f7ab">

<img width="912" alt="image" src="https://github.com/MatthiasGrandl/Loungy/assets/50196894/95ce59e7-b793-4892-afb8-07f251cf9afc">
