### ISSUE TITLE
cargo run dev -> error

### ISSUE THREAD

**Issue by doroved** [MatthiasGrandl/Loungy#2]
<img width="1004" alt="image" src="https://github.com/MatthiasGrandl/loungy/assets/30116541/7fe358a0-e98c-475d-8e78-cbd2ce9b70dd">

**Comment by MatthiasGrandl** [comment]
Sounds like you need to update your rust version. https://github.com/rust-lang/rust/issues/91611

**Comment by hugows** [comment]
@doroved I had the same (two rust versions), in my case what solved was **brew uninstall rust** and then **rustup update**
