### ISSUE TITLE
Occasionally Refresh App Listing

### ISSUE THREAD

**Issue by distek** [MatthiasGrandl/Loungy#36]
LAST ONE, I PROMISE

I noticed that when installing a new application, I have to restart the main Loungy process in order for it to index the recently installed application.

I don't believe it would be a very heavy background job? It would be cool if something like... every 30 seconds (or whatever you feel is appropriate?), have Loungy re-index the various applications directories.

Maybe also just a fsnotify-like job that just forever runs in the background so it's more instant.

Anyway, that's it from me for now! :)

I really do appreciate this app and the work that's been put in to it~

**Comment by MatthiasGrandl** [comment]
It already should be updating the app list once per minute… using fsnotify is an interesting idea though.

**Comment by distek** [comment]
I am likely just wildly impatient then :)

Close this if you'd like, then!

**Comment by MatthiasGrandl** [comment]
Jep just confirmed it, it does a poll once per minute.

**Comment by MatthiasGrandl** [comment]
It's now running on fsnotify!

**Comment by distek** [comment]
You are absolutely killin' it!

I may just finally go learn Rust so I can help in some way lol

Thanks for all you do!
