### ISSUE TITLE
Font looks odd on my build

### ISSUE THREAD

**Issue by hugows** [MatthiasGrandl/loungy#5]
Hey - thanks for this project, a lot of folks will be interested from the recent X post from the Zed guys!

Do you know why my build looks like this - maybe some system font I'm missing? 

![Screenshot 2024-02-07 at 22 19 46](https://github.com/MatthiasGrandl/loungy/assets/11545/b19fb63f-c9cd-4353-a34d-fa7d88634d24)

Cheers!

**Comment by hugows** [comment]
After `brew install --cask homebrew/cask-fonts/font-inter` all good :)

**Comment by MatthiasGrandl** [comment]
The fonts are already bundled now, so that shouldn’t be necessary anymore.
